### ISSUE TITLE
[bug] Nicotine Interaction Info

### ISSUE THREAD

**Issue by shourya-paruvu** [isaakhanimann/psychonautwiki-journal-ios#17]
There seems to be a bug with the interaction checker under the **INFO** section of a journal entry, wherein it says _Nicotine_ has dangerous interactions with _Clonazepam_.

However, upon opening the interaction, it says there are no documented interactions for nicotine.

Screenshots below:

1. INFO
![IMG_0832](https://github.com/user-attachments/assets/ad8bb356-2312-4186-9dd3-e0d72875e518)

2. Interactions
![IMG_0833](https://github.com/user-attachments/assets/81b99a93-b331-444e-b6b0-ab566d7acb92)

**Comment by isaakhanimann** [comment]
The reason it finds a dangerous interaction is because Clonazepam has a dangerous interaction with depressants and Nicotine not only has the stimulant tag but also the depressant tag. It also says in the PW article:
<img width="934" alt="Screenshot 2024-10-30 at 06 29 54" src="https://github.com/user-attachments/assets/eb444ff8-2813-4a98-be3e-7538bd0ad063">

**Comment by shourya-paruvu** [comment]
Ah got it, thanks a ton for the clarification!
